version: '3.8'

services:
  http_server:
    build:
      context: .
      dockerfile: DockerfileHTTP
    ports:
      - "50050:50050"

  grpc_server:
    build:
      context: .
      dockerfile: DockerfileGRPC
    ports:
      - "50051:50051"
